### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by cx-vered-shahar**

### CODE REVIEW

**Comment by veredshahar** [comment]
Logo
**Checkmarx AST \- Scan Summary & Details** - [658c6bf8\-c22a\-45df\-a15f\-831aee446384](https://eu.ast.checkmarx.net/projects/eec7e339-6385-49f1-bde2-8f6929dcecbe/scans?id=658c6bf8-c22a-45df-a15f-831aee446384)
### Violation Summary
HIGH**1 HIGH**
MEDIUM**3 MEDIUM**
### CxAST Results
Severity|Issue|File|Scan Engine
---|---|---|---
HIGH|SQL\_Injection|/encode\.frm: [41](https://github.com/AsafOrgTesting/Sast-Sca-Test-Repo/blob/veredshahar-patch-3//encode.frm#L41), [42](https://github.com/AsafOrgTesting/Sast-Sca-Test-Repo/blob/veredshahar-patch-3//encode.frm#L42)|[CxSAST](https://eu.ast.checkmarx.net/results/658c6bf8-c22a-45df-a15f-831aee446384/eec7e339-6385-49f1-bde2-8f6929dcecbe/sast)
MEDIUM|Hardcoded\_password\_in\_Connection\_String|/encode\.frm: [67](https://github.com/AsafOrgTesting/Sast-Sca-Test-Repo/blob/veredshahar-patch-3//encode.frm#L67)|[CxSAST](https://eu.ast.checkmarx.net/results/658c6bf8-c22a-45df-a15f-831aee446384/eec7e339-6385-49f1-bde2-8f6929dcecbe/sast)
MEDIUM|Parameter\_Tampering|/encode\.frm: [65](https://github.com/AsafOrgTesting/Sast-Sca-Test-Repo/blob/veredshahar-patch-3//encode.frm#L65)|[CxSAST](https://eu.ast.checkmarx.net/results/658c6bf8-c22a-45df-a15f-831aee446384/eec7e339-6385-49f1-bde2-8f6929dcecbe/sast)
MEDIUM|Privacy\_Violation|/encode\.frm: [11](https://github.com/AsafOrgTesting/Sast-Sca-Test-Repo/blob/veredshahar-patch-3//encode.frm#L11), [42](https://github.com/AsafOrgTesting/Sast-Sca-Test-Repo/blob/veredshahar-patch-3//encode.frm#L42)|[CxSAST](https://eu.ast.checkmarx.net/results/658c6bf8-c22a-45df-a15f-831aee446384/eec7e339-6385-49f1-bde2-8f6929dcecbe/sast)

**Comment by olgakil** [comment]
Logo
**Checkmarx AST \- Scan Summary & Details** - [374baebf\-ad68\-4fd4\-9640\-b7a8c9f3fcb3](http://127.0.0.1:8080/projects/9a63a841-c74f-4327-8499-c0d66e2fcc4b/scans?id=374baebf-ad68-4fd4-9640-b7a8c9f3fcb3)
### CxAST Violation Summary
### CxAST Results
Severity|Issue|File|Scan Engine
---|---|---|---

**Comment by olgakil** [comment]
Logo
**Checkmarx AST \- Scan Summary & Details** - [94cdf87f\-4408\-4e54\-80c4\-d75a2f142df7](http://127.0.0.1:8080/projects/9a63a841-c74f-4327-8499-c0d66e2fcc4b/scans?id=94cdf87f-4408-4e54-80c4-d75a2f142df7)
### CxAST Violation Summary
HIGH**1 HIGH**
MEDIUM**3 MEDIUM**
### CxAST Results
Severity|Issue|File|Scan Engine
---|---|---|---
HIGH|SQL\_Injection|/encode\.frm: [41](https://github.com/AsafOrgTesting/Sast-Sca-Test-Repo/blob/veredshahar-patch-3//encode.frm#L41), [42](https://github.com/AsafOrgTesting/Sast-Sca-Test-Repo/blob/veredshahar-patch-3//encode.frm#L42)|[CxAST](http://127.0.0.1:8080/results/94cdf87f-4408-4e54-80c4-d75a2f142df7/9a63a841-c74f-4327-8499-c0d66e2fcc4b/sast)
MEDIUM|Hardcoded\_password\_in\_Connection\_String|/encode\.frm: [67](https://github.com/AsafOrgTesting/Sast-Sca-Test-Repo/blob/veredshahar-patch-3//encode.frm#L67)|[CxAST](http://127.0.0.1:8080/results/94cdf87f-4408-4e54-80c4-d75a2f142df7/9a63a841-c74f-4327-8499-c0d66e2fcc4b/sast)
MEDIUM|Parameter\_Tampering|/encode\.frm: [65](https://github.com/AsafOrgTesting/Sast-Sca-Test-Repo/blob/veredshahar-patch-3//encode.frm#L65)|[CxAST](http://127.0.0.1:8080/results/94cdf87f-4408-4e54-80c4-d75a2f142df7/9a63a841-c74f-4327-8499-c0d66e2fcc4b/sast)
MEDIUM|Privacy\_Violation|/encode\.frm: [11](https://github.com/AsafOrgTesting/Sast-Sca-Test-Repo/blob/veredshahar-patch-3//encode.frm#L11), [42](https://github.com/AsafOrgTesting/Sast-Sca-Test-Repo/blob/veredshahar-patch-3//encode.frm#L42)|[CxAST](http://127.0.0.1:8080/results/94cdf87f-4408-4e54-80c4-d75a2f142df7/9a63a841-c74f-4327-8499-c0d66e2fcc4b/sast)

**Comment by olgakil** [comment]
Logo
**Checkmarx AST \- Scan Summary & Details** - [9e6eaf2c\-6134\-40ed\-926c\-17737c6ff2ca](https://ast-dev.dev.cxast.net/projects/33957af5-6687-442d-a2c0-af5c25aac403/scans?id=9e6eaf2c-6134-40ed-926c-17737c6ff2ca)
### CxAST Violation Summary
HIGH**1 HIGH**
MEDIUM**3 MEDIUM**
### CxAST Results
Severity|Issue|File|Scan Engine
---|---|---|---
HIGH|SQL\_Injection|/encode\.frm: [41](https://github.com/AsafOrgTesting/Sast-Sca-Test-Repo/blob/veredshahar-patch-3//encode.frm#L41), [42](https://github.com/AsafOrgTesting/Sast-Sca-Test-Repo/blob/veredshahar-patch-3//encode.frm#L42)|[CxAST](https://ast-dev.dev.cxast.net/results/9e6eaf2c-6134-40ed-926c-17737c6ff2ca/33957af5-6687-442d-a2c0-af5c25aac403/sast)
MEDIUM|Hardcoded\_password\_in\_Connection\_String|/encode\.frm: [67](https://github.com/AsafOrgTesting/Sast-Sca-Test-Repo/blob/veredshahar-patch-3//encode.frm#L67)|[CxAST](https://ast-dev.dev.cxast.net/results/9e6eaf2c-6134-40ed-926c-17737c6ff2ca/33957af5-6687-442d-a2c0-af5c25aac403/sast)
MEDIUM|Parameter\_Tampering|/encode\.frm: [65](https://github.com/AsafOrgTesting/Sast-Sca-Test-Repo/blob/veredshahar-patch-3//encode.frm#L65)|[CxAST](https://ast-dev.dev.cxast.net/results/9e6eaf2c-6134-40ed-926c-17737c6ff2ca/33957af5-6687-442d-a2c0-af5c25aac403/sast)
MEDIUM|Privacy\_Violation|/encode\.frm: [11](https://github.com/AsafOrgTesting/Sast-Sca-Test-Repo/blob/veredshahar-patch-3//encode.frm#L11), [42](https://github.com/AsafOrgTesting/Sast-Sca-Test-Repo/blob/veredshahar-patch-3//encode.frm#L42)|[CxAST](https://ast-dev.dev.cxast.net/results/9e6eaf2c-6134-40ed-926c-17737c6ff2ca/33957af5-6687-442d-a2c0-af5c25aac403/sast)

**Pull request closed without merging**
